### ISSUE TITLE
Show some loading indicator when cards are loading.

### ISSUE THREAD

**Issue by Brisstor** [howtocards/frontend#50]
Due to slow connection users might think there are no cards, meanwhile they just haven't been loaded yet.
<img width="1380" alt="HowtoCards 2019-05-20 16-28-16" src="https://user-images.githubusercontent.com/9262390/58025087-56f97300-7b1c-11e9-9add-56e2c42a46b7.png">

**Comment by sergeysova** [comment]
@Brisstor Thank you
