### ISSUE TITLE
Home page don't load cards when open direct

### ISSUE THREAD

**Issue by sergeysova** [howtocards/frontend#69]
Steps to reproduce:
1. Open https://test.cards.atomix.team/
2. Wait
3. "Not found" text
4. Go to join
5. Go to home page
6. Cards loaded

Expected:
1. Open https://test.cards.atomix.team/
2. Wait
3. Cards loaded

**Comment by stuneak** [comment]
The selectCards function returns us an empty array.

```js
const selectCards = (props) =>
  createStoreObject({
    cards: $registry.map((reg) => props.ids.map((id) => reg[id])),
    isLoading: cardsFetching.isLoading,
  })

<img width="557" alt="Screen Shot 2019-06-27 at 3 29 17 PM" src="https://user-images.githubusercontent.com/22033385/60266247-5b216900-98f0-11e9-9118-96d4cba8c4b0.png">

**Comment by sergeysova** [comment]
Hmm... No cards with this ids in registry.
