### ISSUE TITLE
Отключить правило проверки defaultProps

### ISSUE THREAD

**Issue by sergeysova** [howtocards/frontend#90]
> Я отключил это линт правило, например. Вот [одна](https://medium.com/@matanbobi/react-defaultprops-is-dying-whos-the-contender-443c19d9e7f1) из куч статей на эту тему.

_Originally posted by @atassis in https://github.com/howtocards/frontend/pull/89_

**Comment by atassis** [comment]
Правило `'react/require-default-props'` если что

**Comment by atassis** [comment]
И да, я бы добавил это правило в конфиг приложения, а не `@atomix/react`, так как проекты, которые используют ваш конфиг, но нуждаются в defaultProps потеряют правило для линтинга
